
//http://en.wikibooks.org/wiki/Polish/Masculine_noun_declension
//http://en.wiktionary.org/wiki/chłopiec
var nounData = [
 [ 'house',      'houses',       'dom',      'domy',      'dom',      'domy',      'm',          'no-agent' ], 
 [ 'cat',        'cats',         'kot',      'koty',      'kota',     'koty',      'm-animate',  'agent' ], 
 [ 'table',      'tables',       'stół',     'stoły',     'stół',     'stoły',     'm',          'no-agent'  ], 
 [ 'store',      'stores',       'sklep',    'sklepy',    'sklep',    'sklepy',    'm',          'no-agent' ], 
 [ 'church',     'churches',     'koscioł',  'koscioły',  'koscioł',  'koscioły',  'm',          'no-agent' ], 
 [ 'car',        'cars',         'samochód', 'samochody', 'samochód', 'samochody', 'm',          'no-agent' ], 
 [ 'bicycle',    'bicycles',     'rower',    'rowery',    'rower',    'rowery',    'm',          'no-agent' ],
 [ 'train',      'trains',       'pociąg',   'pociągi',   'pociąg',   'pociągi',   'm',          'no-agent' ],
 [ 'airplane',   'airplanes',    'samolot',  'samoloty',  'samolot',  'samoloty',  'm',          'no-agent' ], 
 [ 'clock',      'clocks',       'zegar',    'zegary',    'zegar',    'zegary',    'm',          'no-agent' ],
 [ 'watch',      'watches',      'zegarek',  'zegarki',   'zegarek',  'zegarki',   'm',          'no-agent' ],
 [ 'room',       'rooms',        'pokoj',    'pokoje',    'pokoj',    'pokoje',    'm',          'no-agent' ],
 [ 'boy',        'boys',         'chłopiec', 'chłopcy',   'chłopca',  'chłopców',  'm-personal', 'i-agent' ], 
 [ 'pen',        'pens',         'długopis', 'długopisy', 'długopis', 'długopisy', 'm',          'no-agent' ], 
 [ 'shoe',       'shoes',        'but',      'buty',      'but',      'buty',      'm',          'no-agent' ], 
 [ 'sandwich',   'sandwiches',   'kanapka',  'kanapki',   'kanapkę',  'kanapki',   'f',          'no-agent' ],
 [ 'toy',        'toys',         'zabawka',  'zabawki',   'zabawkę',  'zabawki',   'f',          'no-agent' ],
 [ 'bank',       'banks',        'bank',     'banki',     'bank',     'banki',     'm',          'no-agent' ], 
 [ 'ball',       'balls',        'piłka',    'piłki',     'piłkę',    'piłki',     'f',          'no-agent' ],
 [ 'key',        'keys',         'klucz',    'klucze',    'klucz',    'klucze',    'm',          'no-agent' ], 
 [ 'plate',      'plates',       'talerz',   'talerze',   'talerz',   'talerze',   'm',          'no-agent' ], 
 [ 'hat',        'hats',         'kapelusz', 'kapelusze', 'kapelusz', 'kapelusze', 'm',          'no-agent' ], 
 [ 'horse',      'horses',       'koń',      'konie',     'konia',    'konie',     'm-animate',  'agent' ], 
 [ 'woman',      'women',        'kobieta',  'kobiety',   'kobietę',  'kobiety',   'f',          'i-agent' ], 
 [ 'school',     'schools',      'szkoła',   'szkoły',    'szkołę',   'szkoły',    'f',          'no-agent' ], 
 [ 'sister',     'sisters',      'siostra',  'siostry',   'siostrę',  'siostry',   'f',          'i-agent' ], 
 [ 'wife',       'wives',        'żona',     'żony',      'żonę',     'żony',      'f',          'i-agent' ], 
 [ 'cloud',      'clouds',       'chmura',   'chmury',    'chmurę',   'chmury',    'f',          'no-agent' ], 
 [ 'fish',       'fishes',       'ryba',     'ryby',      'rybę',     'ryby',      'f',          'agent' ], 
 [ 'bench',      'benches',      'ławka',    'ławki',     'ławkę',    'ławki',     'f',          'no-agent' ], 
 [ 'book',       'books',        'książka',  'książki',   'książkę',  'książki',   'f',          'no-agent' ], 
 [ 'daughter',   'daughters',    'córka',    'córki',     'córkę',    'córki',     'f',          'i-agent' ], 
 [ 't-shirt',    't-shirs',      'koszulka', 'koszulki',  'koszulkę', 'koszulki',  'f',          'no-agent' ], 
 [ 'skirt',      'skirts',       'spódnica', 'spódnice',  'spódnicę', 'spódnice',  'f',          'no-agent' ], 
 [ 'street',     'streets',      'ulica',    'ulice',     'ulica',    'ulice',     'f',          'no-agent' ], 
 [ 'road',       'roads',        'droga',    'drogi',     'drogę',    'drogi',     'f',          'no-agent' ], 
 [ 'apple',      'apples',       'jabłko',   'jabłka',    'jabłko',   'jabłka',    'n',          'no-agent' ], 
 [ 'chair',      'chairs',       'krzesło',  'krzesła',   'krzesło',  'krzesła',   'n',          'no-agent' ], 
 [ 'soap',       'soaps',        'mydło',    'mydła',     'mydło',    'mydła',     'n',          'no-agent' ], 
 [ 'bed',        'beds',         'łóżko',    'łóżka',     'łóżko',    'łóżka',     'n',          'no-agent' ], 
 [ 'animal',     'animals',      'zwierzę',  'zwierzęta', 'zwierzę',  'zwierzęta', 'n',          'agent' ],
 [ 'father',     'fathers',      'ojciec',   'ojcowie',   'ojca',     'ojców',     'm-personal', 'i-agent' ],
 [ 'husband',    'husbands',     'mąż',      'mężowie',   'męża',     'mężów',     'm-personal', 'i-agent' ],
 [ 'grandpa',    'grandpas',     'dziadek',  'dziadkowie','dziadka',  'dziadków',  'm-personal', 'i-agent' ],
 [ 'newspaper',  'newspapers',   'gazeta',   'gazety',    'gazetę',   'gazety',    'f',          'no-agent' ],
 [ 'letter',     'letters',      'list',     'listy',     'list',     'listy',     'm',          'no-agent' ],    
 [ 'dictionary', 'dictionaries', 'słownik',  'słowniki',  'słownik',  'słowniki',  'm',          'no-agent' ], 
 [ 'sign',       'signs',        'znak',     'znaki',     'znak',     'znaki',     'm',          'no-agent' ],
 [ 'egg',        'eggs',         'jajko',    'jajka',     'jajko',    'jajka',     'n',          'no-agent' ],
 [ 'carrot',     'carrots',      'marchew',  'marchwie',  'marchew',  'marchwie',  'f',          'no-agent' ],
 [ 'sausage',    'sausages',     'kiełbasa', 'kiełbasy',  'kiełbasę', 'kiełbasy',  'f',          'no-agent' ],
 [ 'bridge',     'bridges',      'most',     'mosty',     'most',     'mosty',     'm',          'no-agent' ],
 [ 'friend',     'friends',      'przyjaciel','przyjaciele','przyjaciela','przyjaciół','m-personal',     'i-agent' ],
 [ 'cabbage',    'cabbages',     'kapusta',  'kapusty',   'kapustę',  'kapusty',   'f',          'no-agent' ]
] ;

